### PR TITLE
split out specs to unit and integration

### PR DESCRIPTION
**Pull request by talevy**
just some re-org

### CODE REVIEW

**Comment by purbon** [comment]
LGTM

**Comment by ph** [comment]
@talevy Could you enable redis on travis and run the integration test there?

**Comment by talevy** [comment]
@ph, the integration test is running on travis?

**Comment by ph** [comment]
@talevy Nothing is blocking travis to run the integration test, you just need to make sure the travis yml file install or active redis and define a new test script.

**Comment by talevy** [comment]
@ph from my understanding, I have enabled integration testing on travis

**Comment by ph** [comment]
@talevy My bad I haven't read it carefully enough.

**Pull request merged**
