### PR TITLE
fix LocalJumpError exception

### LINKED ISSUE #26: <LocalJumpError: unexpected next> for all logs
https://github.com/logstash-plugins/logstash-output-redis/blob/v2.0.4/lib/logstash/outputs/redis.rb#L236 triggers a runtime error.

### PR DESCRIPTION
**Pull request by colinsurprenant**
Fixes #26 

Replaced `next` statement by `return` and added specs for regression.

### CODE REVIEW

**Comment by ph** [comment]
Too bad the test isn't easily reproducible.  The change in the context of the issue lgtm and the test run on Travis..  We could probably enable the integration test too.

**Comment by colinsurprenant** [comment]
it is reproducible... thats what the spec does

**Comment by talevy** [comment]
LGTM

**Comment by colinsurprenant** [comment]
bumping version and pushing new plugin version.

**Comment by ph** [comment]
> Too bad the test isn't easily reproducible

I should have clarified that by, I would have expected it to fail on the first iteration not on multiple invocations. This is unclear to me why we aren't hit by this on every call.

**Comment by colinsurprenant** [comment]
@ph you are right, and I could not figure it out. An hypothesis was that it may have been triggered by the JRuby JIT'ing kicking in after N method invocations but I ruled that out because the exception is raised inconsistently, at around 50 invocations but never exactly at the same count.

Also, it is easy to reproduce in standalone using the same type of call chain as in the plugin:
```ruby
def do_nothing
  next
end

def do_block(&block)
  block.call
end

do_block(&method(:do_nothing))
```

This raises the LocalJumpError systematically.

**Comment by colinsurprenant** [comment]
I also tried this which is closer replication of the plugin flow and it also crashes systematically

```ruby
class Codec
  def on_event(&block)
    @on_event = block
  end

  def encode(event)
    @on_event.call(event)
  end
end

class Plugin
  def initialize
    @codec = Codec.new
    @codec.on_event(&method(:crash))
  end

  def receive(event)
    @codec.encode(event)
  end

  private

  def crash(event)
    next
  end
end

Plugin.new.receive(:foo)
```

**Comment by colinsurprenant** [comment]
😓

**Pull request merged**
